- label: "Run tests"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::756629837203:role/catalogue-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: app_test
        command: ["yarn", "test"]

- wait

- label: "Push image"
  branches: "main"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::756629837203:role/catalogue-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - app_prod:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/fake_sierra:ref.${BUILDKITE_COMMIT}
          - app_prod:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/fake_sierra:latest
