- label: "Run tests"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::756629837203:role/catalogue-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: app_test
        command: ["yarn", "test"]
