- label: "Run tests"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::756629837203:role/catalogue-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: app_test
        command: ["yarn", "test"]

- wait

- label: "Push image"
  branches: "main"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::756629837203:role/catalogue-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - app_prod:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/fake_sierra:ref.${BUILDKITE_COMMIT}
          - app_prod:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/fake_sierra:latest

- wait

- label: "Deploy"
  branches: "main"
  concurrency: 1
  concurrency_group: "fake-sierra-deploy"
  plugins:
    - docker#v3.5.0:
        image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.6
        workdir: /repo
        mount-ssh-agent: true
        command: [
            "--confirm",
            "--project-id", "fake_sierra",
            "release-deploy",
            "--from-label", "ref.$BUILDKITE_COMMIT",
            "--environment-id", "public",
            "--description", $BUILDKITE_BUILD_URL,
            "--confirmation-wait-for", 3540 ] # Session times out at 3600s / 1 hour
  agents:
    queue: nano
